site_name: FAS OnDemand User Guide
site_url: https://fasrc.github.io/fas-ondemand-user-guide/
nav:
  - Home: index.md
  - First time launch: firstlaunch.md
  - A brief tour: tour.md
  - Storage: storage.md
  - Interactive Applications:
    - Jupyter Notebooks: jupyter.md
    - Rstudio Server: rstudio.md
    - Kubernetes Applications (beta): kubernetes.md
    - Additional Resources: additionalresources.md
  - Help:
    - Getting help: help.md
    - System Status: status.md
theme: readthedocs
